patience: 10
serialization_dir: /home/machelreid/results/hiddic/
device: cuda
clip: 5
initial_lr: 0.001
min_lr: 0
lr_patience: 10
keep_all_checkpoints: true
val_data_limit: null
max_epochs: 100
training_data_fraction: null
beam_size: 7
min_length: 1
max_length: 50
n_best: 1
ratio: null
lr_scheduling_metric: perplexity
metric_decreases: true

load_model: null
load_optimizer: null

encoder: bert-base-uncased
encoder_hidden: null
max_layer: 12

decoder: lstm
decoder_embedding_dim: 300
decoder_hidden: 512

datapath: /home/machelreid/data/hiddic/
dataset: null

seed: 12

train_batch_size: 64
valid_batch_size: 40
